// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * POST body for creating a registration code.
 */
export type CreateRegistrationCodeRequest = { max_uses: number | null, lifetime: number | null, };

/**
 * Response carrying a registration code.
 */
export type CreateRegistrationCodeResponse = { code: string, };

/**
 * POST body for starting a session.
 */
export type LoginRequest = { username: string, password: string, };

/**
 * Response carrying a session token.
 */
export type LoginResponse = { token: string, };

/**
 * POST body for creating an account.
 */
export type RegisterRequest = { registration_code: string, username: string, display_name: string, password: string, };

/**
 * Response carrying a new account's id and its first session token.
 */
export type RegisterResponse = { id: string, session_token: string, };

/**
 * DELETE body for revoking a registration code.
 */
export type RevokeRegistrationCodeRequest = { code: string, };
