// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A stored file, as sent to clients.
 */
export type FileResponse = { id: string, filename: string, mime: string, byte_size: number, };
