// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file as a message attaches it.
 */
export type AttachmentResponse = { id: string, filename: string, mime: string, byte_size: bigint, spoiler: boolean, };

/**
 * Response carrying when a message was edited.
 */
export type EditMessageResponse = { edited_at: bigint, };

/**
 * A message and the files attached to it.
 */
export type MessageResponse = { seq: bigint, id: string, room_id: string, author_id: string, body: string | null, created_at: bigint, edited_at: bigint | null, deleted_at: bigint | null, attachments: Array<AttachmentResponse>, };
