// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * DELETE body naming which subscription to remove.
 */
export type UnsubscribeRequest = { endpoint: string, };
