// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Permission, Visibility } from "../shared";

/**
 * POST body for creating a room
 */
export type CreateRoomRequest = { name: string, visibility: Visibility, default_permissions: Array<Permission>, claim_all: boolean, };

/**
 * Response carrying the id of a newly created room
 */
export type CreateRoomResponse = { id: string, };

/**
 * A room, as the discoverable directory sees it
 */
export type DiscoverableRoomResponse = { id: string, name: string, visibility: Visibility, created_at: number, };

/**
 * A room, as the caller's own room list sees it
 */
export type MyRoomResponse = { id: string, name: string, visibility: Visibility, mutation_seq: number, };
