// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Visibility } from "../shared";

/**
 * A room, as the discoverable directory sees it
 */
export type DiscoverableRoomResponse = { id: string, name: string, visibility: Visibility, created_at: bigint, };

/**
 * A room, as the caller's own room list sees it
 */
export type MyRoomResponse = { id: string, name: string, visibility: Visibility, mutation_seq: bigint, };
