// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Notify, Permission, Visibility } from "../shared";

/**
 * POST body for creating a room
 */
export type CreateRoomRequest = { name: string, visibility: Visibility, default_permissions: Array<Permission>, claim_all: boolean, };

/**
 * Response carrying the id of a newly created room
 */
export type CreateRoomResponse = { id: string, };

/**
 * A room, as the discoverable directory sees it
 */
export type DiscoverableRoomResponse = { id: string, name: string, visibility: Visibility, created_at: number, };

/**
 * One member of a room, with their resolved permissions.
 */
export type Entry = { user_id: string, permissions: Array<Permission>, granted_at: number, 
/**
 * Present on a caller's own row, members never sees another's
 */
notify: Notify | null, };

/**
 * A room
 */
export type RoomResponse = { id: string, name: string, visibility: Visibility, mutation_seq: number, };
