// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * General server information and limits clients need to know about
 */
export type ServerInfo = { name: string, version: string, kind: string, description: string, 
/**
 * Ids one user lookup may carry
 */
limit_users_lookup: number, };
