// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalRole, LinkedAccount, Status } from "../shared";

/**
 * PATCH body for the caller's own preferences. An absent field is left as it stands
 */
export type PreferencesPatch = { status: Status | null, room_layout: string | null, };

/**
 * The caller's own preferences
 */
export type PreferencesResponse = { status: Status, room_layout: string, };

/**
 * PATCH body for a user's own profile. An absent field is left as it stands.
 */
export type ProfilePatch = { display_name: string | null, 
/**
 * Empty string clears the text
 */
description: string | null, 
/**
 * Nil UUID clears the avatar
 */
avatar_file_id: string | null, 
/**
 * Nil UUID clears the banner
 */
banner_file_id: string | null, };

/**
 * A user's profile
 */
export type UserProfileResponse = { id: string, username: string, display_name: string, description: string, avatar_file_id: string | null, banner_file_id: string | null, global_role: GlobalRole, created_at: bigint, deleted_at: bigint | null, links: Array<LinkedAccount>, };
