// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One file as a message attaches it.
 */
export type AttachmentResponse = { id: string, filename: string, mime: string, byte_size: bigint, spoiler: boolean, };
