// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AttachmentResponse } from "./AttachmentResponse";

/**
 * A message and the files attached to it.
 */
export type MessageResponse = { seq: bigint, id: string, room_id: string, author_id: string, body: string | null, created_at: bigint, edited_at: bigint | null, deleted_at: bigint | null, attachments: Array<AttachmentResponse>, };
