// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user's server-wide role, stored as an integer. (PERMANENT)
 */
export type GlobalRole = "owner" | "admin" | "member" | "visitor";

/**
 * A `linked_accounts` row.
 */
export type LinkedAccount = { platform: Platform, 
/**
 * Name shown for the account
 */
handle: string, };

/**
 * A game service an account is linked to, stored as an integer. (PERMANENT)
 */
export type Platform = "xbox" | "steam";
