// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Name, version, kind, and description of this server.
 */
export type ServerInfo = { name: string, version: string, kind: string, description: string, };
