// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A named group of rooms in a user's room list layout
 */
export type Folder = { name: string, rooms: Array<string>, collapsed: boolean, };

/**
 * A user's server-wide role, stored as an integer. (PERMANENT)
 */
export type GlobalRole = "owner" | "admin" | "member" | "visitor";

/**
 * A `linked_accounts` row.
 */
export type LinkedAccount = { platform: Platform, 
/**
 * Name shown for the account
 */
handle: string, };

export type Notify = "none" | "mentions" | "all";

export type Permission = "post" | "attach" | "commands" | "delete_msg" | "invite" | "rename" | "ban" | "grant" | "delete_room" | "connect" | "speak" | "mute" | "video" | "screenshare";

/**
 * A game service an account is linked to, stored as an integer. (PERMANENT)
 */
export type Platform = "xbox" | "steam";

/**
 * One entry in a user's room list layout
 */
export type RoomListItem = string | Folder;

/**
 * What a user asks to appear as while connected, stored as an integer. (PERMANENT)
 */
export type Status = "online" | "busy" | "away" | "invisible";

/**
 * How a room is discovered and entered, stored as an integer. (PERMANENT)
 */
export type Visibility = "public" | "locked" | "hidden";
