// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a room is discovered and entered
 */
export enum Visibility { "public" = "public", "locked" = "locked", "hidden" = "hidden" }

/**
 * How a user appears to others
 */
export enum Status { "online" = "online", "busy" = "busy", "away" = "away", "offline" = "offline" }

/**
 * A game service an account is linked to
 */
export enum Platform { "xbox" = "xbox", "steam" = "steam" }

/**
 * A user's server-wide role
 */
export enum GlobalRole { "owner" = "owner", "admin" = "admin", "member" = "member", "visitor" = "visitor" }

/**
 * A named group of rooms in a user's room list layout
 */
export type Folder = { name: string, rooms: Array<string>, collapsed: boolean, };

/**
 * A `linked_accounts` row.
 */
export type LinkedAccount = { platform: Platform, 
/**
 * Name shown for the account
 */
handle: string, };

/**
 * One entry in a user's room list layout, room ID and possible folder it's in
 */
export type RoomListItem = string | Folder;

export enum Permission { "post" = "post", "attach" = "attach", "commands" = "commands", "delete_msg" = "delete_msg", "invite" = "invite", "rename" = "rename", "ban" = "ban", "grant" = "grant", "delete_room" = "delete_room", "connect" = "connect", "speak" = "speak", "mute" = "mute", "video" = "video", "screenshare" = "screenshare" }

export enum Notify { "none" = "none", "mentions" = "mentions", "all" = "all" }
