// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One browser a push message is sent to.
 */
export type Subscription = { endpoint: string, p256dh: Array<number>, auth: Array<number>, };
