// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Platform, Status } from "../shared";

/**
 * What a user is connected from, for a client to show beside their status.
 */
export type Device = "windows" | "macos" | "linux" | "android" | "ios" | "chrome" | "desktop" | "mobile" | "tablet";

/**
 * What a linked account last reported about the user who owns it.
 */
export type GameActivity = { platform: Platform, status: GamePresence, 
/**
 * Name of the game
 */
title: string | null, 
/**
 * What the game says they are doing
 */
activity: string | null, };

/**
 * How a linked game account appears to someone sharing a room with it.
 */
export type GamePresence = "Online" | "Offline" | "Away";

/**
 * One browser a push message is sent to.
 */
export type Subscription = { endpoint: string, p256dh: Array<number>, auth: Array<number>, };

/**
 * A user and the linked account they are on.
 */
export type UserGamePresence = { user_id: string, platform: Platform, status: GamePresence, 
/**
 * Name of the game
 */
title: string | null, 
/**
 * What the game says they are doing
 */
activity: string | null, };

/**
 * A user and what the reader is told to show for them.
 */
export type UserPresence = { user_id: string, status: Status, 
/**
 * Unset until the user's client declares one
 */
device: Device | null, };
